/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;




/**
 *
 * @author Samuel
 */
public class SeleccionarNivelPanel extends javax.swing.JPanel {



    

    /**
     * Creates new form SeleccionarNivel
     */
    
    public SeleccionarNivelPanel() {
        
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SeleccionarNivel = new javax.swing.JLabel();
        Nivel2Boton = new javax.swing.JButton();
        Nivel3Boton = new javax.swing.JButton();
        Nivel1Boton = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(53, 68, 139));

        SeleccionarNivel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        SeleccionarNivel.setForeground(new java.awt.Color(255, 255, 255));
        SeleccionarNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SeleccionarNivel.setText("Seleccionar Nivel");

        Nivel2Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/City_level.png"))); // NOI18N
        Nivel2Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nivel2BotonActionPerformed(evt);
            }
        });

        Nivel3Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Forest_level.png"))); // NOI18N
        Nivel3Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nivel3BotonActionPerformed(evt);
            }
        });

        Nivel1Boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Clouds_Level.png"))); // NOI18N
        Nivel1Boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nivel1BotonActionPerformed(evt);
            }
        });

        BotonVolver.setBackground(new java.awt.Color(53, 68, 139));
        BotonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/button_volver.png"))); // NOI18N
        BotonVolver.setBorder(null);
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(SeleccionarNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(Nivel1Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(Nivel2Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Nivel3Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(SeleccionarNivel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Nivel2Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(BotonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Nivel1Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Nivel3Boton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))))))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void Nivel3BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nivel3BotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nivel3BotonActionPerformed

    private void Nivel2BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nivel2BotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nivel2BotonActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void Nivel1BotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nivel1BotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nivel1BotonActionPerformed

    public JButton getBotonVolver() {
        return BotonVolver;
    }

    public JButton getNivel1Boton() {
        return Nivel1Boton;
    }

    public JButton getNivel2Boton() {
        return Nivel2Boton;
    }

    public JButton getNivel3Boton() {
        return Nivel3Boton;
    }

    public JLabel getSeleccionarNivel() {
        return SeleccionarNivel;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVolver;
    private javax.swing.JButton Nivel1Boton;
    private javax.swing.JButton Nivel2Boton;
    private javax.swing.JButton Nivel3Boton;
    private javax.swing.JLabel SeleccionarNivel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
