/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author camilosar
 */
public class VistaGameOver extends javax.swing.JPanel {

    public JButton getBotonImagen() {
        return BotonImagen;
    }


  

    /**
     * Creates new form VistaGameOver
     */
    public VistaGameOver() {
        initComponents();
    }

    public JButton getBotonSalir() {
        return BotonSalir;
    }

    public JButton getBotonVolverAJugar() {
        return BotonVolverAJugar;
    }

    public JLabel getLabelPuntaje() {
        return LabelPuntaje;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();
        BotonVolverAJugar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LabelPuntaje = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BotonImagen = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(53, 68, 139));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        BotonSalir.setBackground(new java.awt.Color(53, 68, 139));
        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/button_salir.png"))); // NOI18N
        BotonSalir.setBorder(null);

        BotonVolverAJugar.setBackground(new java.awt.Color(53, 68, 139));
        BotonVolverAJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/button_volver-a-jugar.png"))); // NOI18N
        BotonVolverAJugar.setBorder(null);
        BotonVolverAJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverAJugarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Puntaje");

        LabelPuntaje.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LabelPuntaje.setForeground(new java.awt.Color(255, 255, 255));
        LabelPuntaje.setText("0");

        jPanel2.setMaximumSize(new java.awt.Dimension(554, 601));
        jPanel2.setPreferredSize(new java.awt.Dimension(554, 600));
        jPanel2.setLayout(new java.awt.BorderLayout());

        BotonImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/DerrotaBackground.png"))); // NOI18N
        jPanel2.add(BotonImagen, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(LabelPuntaje)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonSalir)
                            .addComponent(BotonVolverAJugar))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LabelPuntaje))
                .addGap(82, 82, 82)
                .addComponent(BotonVolverAJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(BotonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverAJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverAJugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVolverAJugarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonImagen;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonVolverAJugar;
    private javax.swing.JLabel LabelPuntaje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
